[package]
name = "cmdrunner"
version = "0.6.0"
edition = "2021"

[dependencies]
eframe = "0.29"
tray-icon = "0.19"
muda = "0.15"
rfd = "0.15"
toml = "0.8"
serde = { version = "1", features = ["derive"] }
windows-sys = { version = "0.59", features = [
    "Win32_Foundation",
    "Win32_UI_WindowsAndMessaging",
] }

[profile.release]
opt-level = 3
lto = true
strip = true
